export const data = [
    {
        id:1,
        text:"Conocimientos",
        img:require('./assets/cono.png')
    },
    {
        id:1,
        text:"Inglés",
        img:require('./assets/Ingless.png')
    },
    {
        id:1,
        text:"Psicotécnicos",
        img:require('./assets/Psicotecnicos.png')
    },
    {
        id:1,
        text:"Ortografía",
        img:require('./assets/ortografia.png')
    },
]