import { Platform, StyleSheet } from 'react-native';
import {
  heightPercentageToDP,
  widthPercentageToDP,
} from '../../Component/MakeMeResponsive';
import { fonts } from '../../utils';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  topView: {
    // flexDirection: 'row',
    // alignItems: 'center',
    // justifyContent: 'space-between',
    // width: '100%',
    // height: '15%',
    // marginLeft: widthPercentageToDP(2),
    //backgroundColor: 'red',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: Platform.OS === 'android' ? 0 : widthPercentageToDP(0.5)
  },
  playPauseView: {
    width: widthPercentageToDP(30),
    flexDirection: 'row',
  },
  timerView: {
    width: widthPercentageToDP(30),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  timerText: {
    fontSize: widthPercentageToDP(5),
    fontFamily: fonts.elegance,
    color: '#000',
    textAlign: 'center',
  },
  logo: {
    width: widthPercentageToDP(55),
    height: widthPercentageToDP(13),
  },
  logo2: {
    width: heightPercentageToDP(55),
    height: widthPercentageToDP(12),
    //marginRight: heightPercentageToDP(2),
  },
  logoView: {
    flexDirection: 'row-reverse',
  },
  innerLogoView: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  endReview: {
    marginLeft: widthPercentageToDP(2),
    marginRight: widthPercentageToDP(2),
  },
  endReviewText: {
    fontSize: widthPercentageToDP(4),
    fontFamily: fonts.elegance,
    color: '#000',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  middleView: {
    marginTop: heightPercentageToDP(1),
    marginLeft: widthPercentageToDP(3),
    marginRight: widthPercentageToDP(5),
    width: '100%',
    height: '91%',
    //flex
  },
  bottomView: {
    //flex: 0,
    // marginLeft: widthPercentageToDP(5),
    // alignItems:"center",
    //marginBottom: widthPercentageToDP(1)
    position: 'absolute',
    bottom: '1%',
    marginLeft: widthPercentageToDP(2),
    marginRight: widthPercentageToDP(2),
  },
  btnImage: {
    width: widthPercentageToDP(10),
    height: widthPercentageToDP(10),
    marginLeft: widthPercentageToDP(1),
  },
  loading: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalMain: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  innerModal: {
    width: '100%',
    height: '100%',
    marginBottom: widthPercentageToDP(10),
    marginLeft: widthPercentageToDP(5),
    marginRight: widthPercentageToDP(5),
  },
  crossBtn: {
    width: widthPercentageToDP(10),
    height: widthPercentageToDP(10),
    borderRadius: widthPercentageToDP(10) / 2,
    backgroundColor: '#cccccc',
    marginLeft: widthPercentageToDP(5),
    marginTop: widthPercentageToDP(5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuBtn: {
    width: widthPercentageToDP(10),
    height: widthPercentageToDP(10),
    backgroundColor: 'red',
  },
  btnView: {
    width: '30%',
    height: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    //paddingHorizontal: widthPercentageToDP(1),
  },
  menuButton: {
    width: widthPercentageToDP(10),
    height: widthPercentageToDP(10),
  },
  menuButton2: {
    width: heightPercentageToDP(10),
    height: heightPercentageToDP(10),
    //backgroundColor: 'yellow',
  },
  blockButton: {
    width: widthPercentageToDP(7),
    height: widthPercentageToDP(7),
    marginLeft: widthPercentageToDP(1),
  },
  blockButton2: {
    width: heightPercentageToDP(10),
    height: heightPercentageToDP(10),
    marginLeft: heightPercentageToDP(1),
    //backgroundColor: 'red',
  },
  modalMain2: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  innerModal2: {
    // width: '100%',
    // height: '100%',
    //flex: 1,
    marginBottom: widthPercentageToDP(10),
    marginLeft: widthPercentageToDP(5),
    marginRight: widthPercentageToDP(5),
  },
  navigation: {
    width: widthPercentageToDP(70),
    height: widthPercentageToDP(100),
  },
  topModal: {
    flexDirection: 'row-reverse',
    marginTop: heightPercentageToDP(5),
    marginRight: widthPercentageToDP(10),
  },
  navigationHeader: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginRight: widthPercentageToDP(5),
    // position: "absolute",
    // right: "4%",
    // top: "4%"
  },
  loaderStyle: {
    width: widthPercentageToDP(8),
    height: widthPercentageToDP(8),
    marginRight: widthPercentageToDP(3),
  },
  mainModalView: {
    //flex: 1,
    marginTop: heightPercentageToDP(2),
    width: widthPercentageToDP(100),
  },
  jump: {
    height: widthPercentageToDP(50),
  },
  timeView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    //justifyContent:"space-around",
    alignItems: 'center',
  },
  timeText: {
    fontSize: widthPercentageToDP(4),
    fontFamily: fonts.elegance,
    color: '#ffff',
    //textAlign: "left",
    marginLeft: widthPercentageToDP(1.5),
  },
  timeValue: {
    fontSize: widthPercentageToDP(4.5),
    fontFamily: fonts.novaBold,
    color: '#ffff',
    width: widthPercentageToDP(14),
  },
  timeValue2: {
    fontSize: widthPercentageToDP(4.5),
    width: widthPercentageToDP(15),
    fontFamily: fonts.novaBold,
    color: '#ffff',
    marginLeft: widthPercentageToDP(4),
  },
  timeValue3: {
    width: widthPercentageToDP(5),
    fontSize: widthPercentageToDP(4.5),
    fontFamily: fonts.novaBold,
    color: '#ffff',
    marginLeft: widthPercentageToDP(5),
  },
  timeValue4: {
    width: widthPercentageToDP(6),
    fontSize: widthPercentageToDP(4.5),
    fontFamily: fonts.novaBold,
    color: '#ffff',
    marginLeft: widthPercentageToDP(10.5),
  },
  timeValue5: {
    width: widthPercentageToDP(6),
    fontSize: widthPercentageToDP(4.5),
    fontFamily: fonts.novaBold,
    color: '#ffff',
    marginLeft: widthPercentageToDP(10),
  },
  timeValue6: {
    width: widthPercentageToDP(6),
    fontSize: widthPercentageToDP(4.5),
    fontFamily: fonts.novaBold,
    color: '#ffff',
    marginLeft: widthPercentageToDP(5),
  },
  midView: {
    width: widthPercentageToDP(45),
    flexDirection: 'row',
    flexWrap: 'wrap',
    //justifyContent:"space-between",
    alignItems: 'center',
    marginLeft: widthPercentageToDP(8),
    //backgroundColor:"red"
  },
  mnTime: {
    fontSize: widthPercentageToDP(4.5),
    fontFamily: fonts.elegance,
    color: '#ffff',
    marginLeft: widthPercentageToDP(1),
  },
  rejectView: {
    flex: 1,
    backgroundColor: 'rgba(1,1,1,0.5)',
  },
  rejectContainer: {
    width: heightPercentageToDP(80),
    height: widthPercentageToDP(75),
    backgroundColor: '#fff',
    borderRadius: heightPercentageToDP(2),
    alignSelf: 'center',
    marginTop: Platform.OS === 'android' ? widthPercentageToDP(3) : widthPercentageToDP(5),
  },
  rejectBottom: {
    width: '100%',
    height: '18%',
    position: 'absolute',
    bottom: '0%',
    // borderTopWidth: heightPercentageToDP(0.2),
    // borderTopColor: '#000',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderBottomLeftRadius: heightPercentageToDP(2),
    borderBottomRightRadius: heightPercentageToDP(2),
  },
  rejectBtn: {
    fontSize: heightPercentageToDP(2),
    fontFamily: fonts.novaBold,
    color: '#ffff',
  },
  rejectDescription: {
    fontSize: heightPercentageToDP(2),
    fontFamily: fonts.novaBold,
    color: '#000',
    paddingTop: heightPercentageToDP(1.5),
    paddingLeft: heightPercentageToDP(5),
  },
  listOptions: {
    width: heightPercentageToDP(80),
    height: widthPercentageToDP(47),
    //backgroundColor: 'red',
  },
  inputStyle: {
    width: heightPercentageToDP(65),
    height: widthPercentageToDP(15),
    //marginTop: heightPercentageToDP(1),
    alignSelf: 'center',
    fontSize: heightPercentageToDP(2),
    fontFamily: fonts.novaRegular,
    color: '#000',
    //backgroundColor: 'red',
  },
  optionsStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: heightPercentageToDP(3),
    marginTop: heightPercentageToDP(0.5),
  },
  rejectItems: {
    fontSize: heightPercentageToDP(2),
    fontFamily: fonts.novaRegular,
    color: '#000',
    marginLeft: heightPercentageToDP(0.4),
  },
});
